Better CI caching
Anastasia-Labs/smart-handles pull request #25
Opened 2023-12-16 16:40 UTC by mpetruska

* [x] better caching/build solution
* [x] clean github cache workflow
* [x] ready for review/merge
----
Note:
The GitHub cache action will report restore failure even when the restore was successful. This is caused by tar unable to extract files that are already in the nix store, but the other files are restored. There is no easy way to fix this at the moment, because the GitHub toolkit insist on using a shitty glob implementation, a regex file path filter would be much better. Apart from the misleading report (and that the unneeded nix packages take place in the cache), there seems to be no drawback at the moment.

2023-12-18 14:06 UTC, solidsnakedev requested changes

2023-12-18 14:06 UTC, solidsnakedev commented on .github/workflows/main.yaml
I understand the Github cache problem, but I don't understand using a different nix installer.
Also the custom configs are already defined in flake.nix
https://github.com/Anastasia-Labs/smart-handles/blob/86811ba10a5a12af8d597bb27746dca2ccce53e3/flake.nix#L4-L12

2023-12-18 14:06 UTC, solidsnakedev commented on Makefile
`nix flake check --accept-flake-config` , should be enough ?

2023-12-19 11:46 UTC, mpetruska commented on .github/workflows/main.yaml
The nix quick install action puts the nix directory The nix store (/nix/store) is owned by the unprivileged runner user, whereas the other one does not. This makes caching on a file level impossible with the Determinate nix installer.

2023-12-19 11:47 UTC, mpetruska commented on .github/workflows/main.yaml
For reference: https://github.com/Anastasia-Labs/smart-handles/actions/runs/7261274194/job/19782114729?pr=25

2023-12-19 13:21 UTC, mpetruska commented on Makefile
Removed nix config from `main.yaml`.

2023-12-19 15:58 UTC, solidsnakedev approved these changes

2023-12-19 15:58 UTC, merged